language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"


env:
  - DJANGO=1.5.12
  - DJANGO=1.6.9
  - DJANGO=1.7.8
  - DJANGO=1.8.1


matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.8
    - python: "2.6"
      env: DJANGO=1.8.1


install:
  - pip install -q Django==$DJANGO
  - pip install -q requests
  - pip install -q flake8
  - pip install -q python-coveralls coverage
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"
  - python setup.py install


before_script:
  - make flake8


after_success:
  - make coveralls

script:
  - make coverage

